accounts/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")

]

apthunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:id>/', views.detail, name='detail'),
    path('addlisting/', views.add_listing, name="add_listing"),
    path('editlisting/<int:id>', views.edit_listing, name="edit_listing"),
    path('deletelisting/<int:id>', views.delete_listing, name="delete_listing"),
    path('addreview/<int:id>', views.add_review, name="add_review"),
    path('editreview/<int:listing_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('deletereivew/<int:listing_id>/<int:review_id>/', views.delete_review, name="delete_review")
]

main/models.py
#from djmoney.models.fields import MoneyField
from phone_field import PhoneField
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

# Potentially for auto-complete
HOOD_CHOICES=(
    ("Lower East Side", "Lower East Side"),
    ("Financial District", "Financial District"),
    ("Chelsea", "Chelsea"),
    ("West Village", "West Village"),
    ("East Village", "East Village"),
    ("SoHo", "SoHo"),
    ("Tribeca", "Tirbeca"),
    ("Hell's Kitchen", "Hell's Kitchen"),
    ("Midtown", "Midtown"),
    ("Upper West Side", "Upper West Side"),
    ("Flatiron", "Flatiron")
)

# Create your models here.
class Listing(models.Model):
    name = models.CharField(max_length=300)
    link = models.URLField(max_length=300)
    neighborhood = models.CharField(max_length=300, choices=HOOD_CHOICES)
    beds = models.IntegerField()
    baths = models.IntegerField()
    #price = MoneyField(max_digits=14, decimal_places=0, default_currency='USD')
    price = models.FloatField(default=0)
    # averageRating = models.FloatField(default=0)
    addDate = models.DateTimeField(default=timezone.now)
    phoneNumber = PhoneField(blank=True, help_text='Contact phone number')
    image = models.URLField(default=None, null=True)
    #image = models.ImageField(null=True, blank=True, upload_to="images/")

    def address(self):
        return self.name.split(" #")[0]

    def __str__(self):
        return self.name

    @property
    def averageLocation(self):
        average = self.review_set.aggregate(Avg("rating_location"))['rating_location__avg']
        if average == None:
            average = 0
        average = round(average,2)
        return average

    @property
    def averageLayout(self):
        average = self.review_set.aggregate(Avg("rating_layout"))['rating_layout__avg']
        if average == None:
            average = 0
        average = round(average,2)
        return average

    @property
    def averagePrice(self):
        average = self.review_set.aggregate(Avg("rating_price"))['rating_price__avg']
        if average == None:
            average = 0
        average = round(average,2)
        return average

    @property
    def totalAverage(self):
        average = (self.averageLocation + self.averageLayout + self.averagePrice)/3
        if average == None:
            average = 0
        average = round(average,2)
        return average



class Review(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000, default="No Comment")
    rating = models.FloatField(default=0)
    rating_location = models.FloatField(default=0)
    rating_layout = models.FloatField(default=0)
    rating_price = models.FloatField(default=0)


    def __str__(self):
        return self.user.username

    @property
    def ratingTotal(self):
        average = (self.rating_location + self.rating_layout + self.rating_price)/3
        if average == None:
            average = 0
        average = round(average,2)
        return average

main/forms.py
from django import forms
from django.forms import fields
from .models import *

# listing add form
class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ('name', 
                  'neighborhood', 
                  'beds', 
                  'baths',
                  'price',
                  'link',
                  'image')

# Will eventually want to add rating field for location, layout, and price
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields= ("comment", "rating_location", "rating_layout", "rating_price")
        # fields= ("comment", "rating")

main/views.py
from typing import List
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import F, Avg, Sum

HOOD_CHOICES=[
    "Lower East Side",
    "Financial District",
    "Chelsea",
    "West Village",
    "East Village",
    "SoHo",
    "Tribeca",
    "Hell's Kitchen",
    "Midtown",
    "Upper West Side",
    "Flatiron"
]

# Create your views here.

# STILL NEED TO ADD LOGIN CHECK ON HOME
def home(request):
    if request.user.is_authenticated:
        print(request.GET)
        query = request.GET
        hood = query.get("neighborhood")
        order_by = request.GET.get('order_by', 'addDate')
        allListings = None
        if hood:
            allListings = Listing.objects.filter(neighborhood__icontains=hood)
        else:
            hood=""
            allListings=Listing.objects.all() # select * from Listing

        print(hood)

        if order_by=='rating':
            allListings = allListings.annotate(average_rate = (Avg('review__rating_location') + Avg('review__rating_layout') + Avg('review__rating_price'))/3).order_by("-average_rate")
        elif order_by=='addDate':
            allListings = allListings.order_by("-"+order_by)
        else:
            allListings = allListings.order_by(order_by)

        context = {
            "listings":allListings,
            "hood":hood,
            "hood_choices": HOOD_CHOICES
        }

        return render(request, 'main/index.html', context)
    else:
        # if not logged in
        return redirect("accounts:login")

# detail page
def detail(request, id):
    listing = Listing.objects.get(id=id) # select * from listing where id=id
    reviews = Review.objects.filter(listing = id).order_by("-comment")
    print(listing.averageLocation)
    # agg = listing.averageLocation + listing.averageLocation 

    # Not necessary but here from earlier
    average = reviews.aggregate(Avg("rating"))['rating__avg']
    if average == None:
        average = 0
    average = round(average,2)
    context = {
        "listing": listing,
        "reviews": reviews,
        #"average": agg
    }
    return render(request, 'main/details.html', context)

# add listing to database
def add_listing(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = ListingForm(request.POST or None)

                # Check if form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:home")
            else:
                form = ListingForm()
            return render(request, 'main/addlisting.html', {"form": form, "controller": "Add Listing"})
        
        # if not admin
        else:
            return redirect("main:home")

    # if not logged in
    return redirect("accounts:login")


# edit listing
def edit_listing(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the listing linked with id
            listing = Listing.objects.get(id=id)

            # form check
            if request.method == "POST":
                form = ListingForm(request.POST or None, instance=listing)
                # Check if form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:detail", id)
            else:
                form = ListingForm(instance=listing) 
            return render(request, 'main/addlisting.html', {"form": form, "controller": "Edit Listing"})
        # if not admin
        else:
            return redirect("main:detail", id)

    # if not logged in
    return redirect("accounts:login")



# delete listing
def delete_listing(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:    
            # Get listing
            listing = Listing.objects.get(id=id)

            # delete the listing
            listing.delete()
            return redirect("main:home")
        else:
            return redirect("main:detail", id)
            
    # if not logged in
    return redirect("accounts:login")

# review listing
def add_review(request, id):
    if request.user.is_authenticated:
        listing = Listing.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data=form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating_location = request.POST["rating_location"]
                data.rating_layout = request.POST["rating_layout"]
                data.rating_price = request.POST["rating_price"]
                data.user = request.user
                data.listing = listing
                data.save()
                return redirect("main:detail", id)
        else:
            form = ReviewForm()
        return render(request, "main/details.html", {"form": form})
    else:
        return redirect("accounts:login")

# edit reviews
def edit_review(request, listing_id, review_id):
    if request.user.is_authenticated:
        listing = Listing.objects.get(id=listing_id)
        # review
        review = Review.objects.get(listing=listing, id=review_id)
        #print(review.ratingTotal)

        # check if the review was done by logged on user
        if request.user == review.user:
            # grant permission to edit
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 5) or (data.rating < 0):
                        error = "Out of range. Please select rating from 0 to 5" 
                        return render(request, "main/editreview.html", {"error": error, "form": form})
                    else:
                        data.save()
                        return redirect("main:detail", listing_id)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html', {'form': form})
        else:
            return redirect("main:detail", listing_id)
    else:
        return redirect("accounts:login")

# delete reviews
def delete_review(request, listing_id, review_id):
    if request.user.is_authenticated:
        listing = Listing.objects.get(id=listing_id)
        # review
        review = Review.objects.get(listing=listing, id=review_id)

        # check if the review was done by logged on user
        if request.user == review.user:
            # grant permission to delete
            review.delete()

        return redirect("main:detail", listing_id)
    else:
        return redirect("accounts:login")

main/templates/main/addlisting.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="{{ controller }}" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
    <title>Apartment Hunt NYC</title>
   
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'main:home' %}">NYC Apartment Hunt</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            {% if request.user.is_superuser%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:add_listing' %}">Add Listing</a>
            </li> 
            {% endif %}           

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
              </div>
            </li>         
          </ul>
          <ul class="navbar-nav nav-right">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sort By
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="?order_by=price&neighborhood={{ hood }}">Price</a>
                <a class="dropdown-item" href="?order_by=rating&neighborhood={{ hood }}">Rating</a>
              </div>
            </li>
          </ul>
         

          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url "main:home" %}">
            {% if hood %}
            <script>window.alert(hood);</script>
            <input list="options" class="form-control mr-sm-2" type="search" placeholder="Neighborhood" aria-label="Search" name="neighborhood" value="{{ hood }}">
            <datalist id="options">
              {% for choice in hood_choices %}
                <option>{{ choice}}</option>
              {% endfor %}
            </datalist>
            {% else %}
            <input list="options" class="form-control mr-sm-2" type="search" placeholder="Neighborhood" aria-label="Search" name="neighborhood">
            <datalist id="options">
              {% for choice in hood_choices %}
                <option>{{ choice }}</option>
              {% endfor %}
            </datalist>
            {% endif %}
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>


            {% else %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
          </ul>
            {% endif %}
      </nav>

    {% block content %}

    {% endblock %}
    
    <!-- Optional JavaScript -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>

</html>

main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

<br>
<div class="container">
    <div class="card">
        <div class="card-body" id="det_backdrop">
        <div class="row">
            <div class="col-md-4">
                <a href="{{listing.image}}" title="click to enlarge">
                    <img src="{{listing.image}}" alt="{{ listing.name }}" class="img-fluid" id="img_det">
                </a>
            </div>
            <div class="col-md-8">
                
                <h3><a href="{{ listing.link }} " target="_blank">{{ listing.name }}</a></h3>
                <h5><b>{{ listing.neighborhood }}</b></h5>
                <h5>Price: ${{ listing.price|floatformat:0 }} </h5>
                <h5>Beds: {{ listing.beds }} </h5>
                <h5>Baths: {{ listing.baths }} </h5>
                <a href="http://maps.google.com/?q={{ listing.address }},+New+York,+NY" target="_blank">See on map</a>
                <br>
                <br>
                <h5><b><u>Rating Average </u></b></h5>
                <h5>Location: {{ listing.averageLocation }}/5</h5>
                <h5>Layout: {{ listing.averageLayout}}/5</h5>
                <h5>Price: {{ listing.averagePrice}}/5</h5>
                <br>
                
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser%}
                        <a href="{% url 'main:edit_listing' listing.id %}" class="btn btn-warning">Edit Listing</a>
                        <a href="{% url 'main:delete_listing' listing.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete?');">Delete Listing</a>
                    {% endif %}
                {% endif %}
                <br><br>
                <h6>Added: {{ listing.addDate }}</h6>

            </div>
        </div>
        </div>
    </div>

    <br>
    {% if request.user.is_superuser%}
    <form action="{% url 'main:add_review' listing.id %}" method="POST">
        {% csrf_token %}
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Review</h3>
            <br>
            
            <div class="container">
                <div class="row">
                    <div class="col align-self-start">
                        <label for="rating_location"><strong>Location</strong></label><br>
                        <input type="range" id="rangeInput1" 
                            name="rating_location" min="0" max="5" value="0" step="0.5"
                            oninput="amount1.value=rangeInput1.value">                                                       
                
                        <output name="amount1" id="amount1" for="rangeInput1">0</output>
                    </div>
                    
                    <div class="col align-self-center">
                        <label for="rating_layout"><strong>Layout</strong></label><br>
                        <input type="range" id="rangeInput2" 
                            name="rating_layout" min="0" max="5" value="0" step="0.5"
                            oninput="amount2.value=rangeInput2.value">                                                       
                
                        <output name="amount2" id="amount2" for="rangeInput2">0</output>
                    </div>
                   
                    <div class="col align-self-end">
                        <label for="rating_price"><strong>Price</strong></label><br>
                        <input type="range" id="rangeInput3" 
                            name="rating_price" min="0" max="5" value="0" step="0.5"
                            oninput="amount3.value=rangeInput3.value">                                                       
                
                        <output name="amount3" id="amount3" for="rangeInput3">0</output>
                    </div>
                </div>
            </div>
            <br>
            
                <label for="comment">Comments</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control">No Comment</textarea>
               


                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">

            </form>
        </div>
    </div>
    {% endif %}
    
    
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
            <div class="card" style="background-color: #f5eeee;">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h4 class="text-left">{{ review.user.username }}</h4>
                            <br>
                                <h5>Location: {{ review.rating_location|floatformat }}/5</h5>
                                <h5>&nbsp&nbsp  Layout: {{ review.rating_layout|floatformat }}/5</h5>
                                <h5>&nbsp&nbsp&nbsp&nbsp&nbsp Price: {{ review.rating_price|floatformat }}/5</h5>

                            {% if request.user == review.user %}
                            <br>
                            <a href="{% url 'main:edit_review' listing.id review.id%}">Edit</a>
                            <a href="{% url 'main:delete_review' listing.id review.id%}" onclick="return confirm('Are you sure you want to delete?');">Delete</a>
                            {% endif %}
                        </div>
                        <div class="col-md-9">
                            <p>{{ review.comment }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br>
                
            {% endfor %}
        </div>
    </div>
</div>





{% endblock  %}

main/templates/main/editreview.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                {% if error %}
                    <strong style="color: red;"> {{ error }} </strong>
                    <br>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<br>
<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for listing in listings %}
                <div class="col-md-4"> 
                    <div class="card">
                        <div class="card-body">
                            <img src="{{ listing.image }}" alt="" class="img-fluid">
                            <br><br>
                            <h4><a href="{% url 'main:detail' listing.id %}">{{ listing.name }}</a></h4>
                            <h5><b>{{ listing.neighborhood }}</b></h5>
                            <h6>beds: {{ listing.beds }}</h6>
                            <h6>baths: {{ listing.baths }}</h6>
                            <h6>price: ${{ listing.price | floatformat:0 }}</h6>
                            <h6>rating: {{  listing.totalAverage| floatformat }}/5</h6>
                            <br>
                            <i>added: {{ listing.addDate }}</i>
                            
                            
                        </div>
                    </div>
                    <br>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock  %}